### ISSUE TITLE
Use for warping a geospatial raster with leaflet?

### ISSUE THREAD

**Issue by rowanwins** [sakitam-gis/affine#1]
Hi there,

I was wondering if this library could conceivably be used for transforming a raster from one projection to overlay on a WebMercator map?

I noticed the [GIS doco](https://github.com/sakitam-gis/affine#gis) in the readme which returns a geo transform, but I couldn't quite work out the exact approach.

I have an image in EPSG:32753 - WGS 84 / UTM zone 53S which I was hoping to render on a leafletJS map.

````
// Should the bounds be in the native raster projection, or WGS84, or WebMercator??? 
const bounds = [minx, miny, maxx, maxy]

const t = Affine.translation(minx, maxy)
const s = Affine.scale((maxx - minx) / width, (miny - maxy) / height)

const geoTransform = t.multiply(s).toArray()

// Apply the geotransform to a tile canvas

context.transform(
     geoTransform[0],
     geoTransform[1],
     geoTransform[2],
     geoTransform[3],
     geoTransform[4],
     geoTransform[5]
)


L.imageOverlay(imageUrl, wgsBounds)
````

Any tips would be appreciated :)

**Comment by sakitam-fdd** [comment]
@rowanwins you may need is https://gitlab.com/IvanSanchez/arrugator and https://gitlab.com/IvanSanchez/Leaflet.ImageOverlay.Arrugator , is used to process the affine transformation in gdal.

**Comment by rowanwins** [comment]
Thanks for that @sakitam-fdd - I had already experimented with those libraries but they didn't exactly fit my need so I was exploring other options. 

This was what I had achieved with Arrugator, but every now and again it was crashing because of too many webgl instances being drawn (1 for each tile)
https://user-images.githubusercontent.com/6735870/203864906-7cbc9b31-921f-476e-965f-d2a24f41e83f.mp4

**Comment by sakitam-fdd** [comment]
@rowanwins I noticed that it is possible to create a gl instance for each tile now, but there is a limit on the number of gl instances in a page. Is it possible to use a gl context to calculate the position, uv and tile modelMatrix of each tile, and render them in the following ways:
```js
clear();
for(tile in tiles) {
  drawCommand({
     image: tile.image,
     position: tile.position,
     uv: tile.uv,
     modelMatrix: tile.modelMatrix,
     projectionMatrix,
  })
}
```

But it may take some work, this is what I'm doing, but it will take some time
